### ISSUE TITLE
logging should go to stdout/stderr in Procfile

### ISSUE THREAD

**Issue by miguelgrinberg** [brijeshb42/yapper#1]
Hey, very nice project. Wanted to mention that the gunicorn configuration in your Procfile is not going to work well. Sending logs to a file when running in Heroku is not a good idea because the platform is virtualized, Heroku can, at any time, recreate the VM, and what that all files go away.

The recommended approach is to configure the web server to dump logs to stdout/stderr. Heroku captures those and then exposes them through the `heroku logs` command.

Good luck with your project!

**Comment by brijeshb42** [comment]
@miguelgrinberg So nice to hear from you. I will fix change the log to stdout/err from file.
Thanks for the suggestion.
Also can you tell me what would be a good way to support theming in flask (except flask-themes) ?

**Comment by miguelgrinberg** [comment]
For themes I can think of two implementations:

1. Have a `themes` directory where users drop their themes. Each theme will have a root directory (the theme name) and inside `templates` and `static` sub-directories. The application then creates symlinks to these directories in the correct apps' folders using the theme name. So then the templates and static files of a them are available at `theme-name/template-name.html` and `url_for('static', filename='theme-name/filename')`.

2. The other approach is to define a theme as a blueprint. Upon registration the `templates` and `static` directories become available to the application. Note that this option requires some thinking if you serve static files through nginx or other web server since now you need to configure the static folder of the theme as well.

**Comment by brijeshb42** [comment]
@miguelgrinberg I was worried about how we require the template file name before serving a request. So whatever the implementation be, it will enforce the theme developer to have the recommended template file names. I was looking for a way to avoid that.

**Comment by miguelgrinberg** [comment]
If you want to allow the theme author to use any template names, then you can require a configuration file in the theme directory that defines the names of all the templates.

**Comment by brijeshb42** [comment]
@miguelgrinberg that would be a good way. Thanks for the suggestion.
